name: restaurant_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  hidden_drawer_menu: ^3.0.1
  http: any

  cupertino_icons: ^1.0.2
  url_launcher:
  flutter_svg:


  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f2f5f6"
  image: assets/images/logo.png
  android: true
  ios: true
  web: true
  branding: null

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/logo.png
     - assets/images/maroua.png
     - assets/images/wiame.jpg
     - assets/images/flutter.png
     - assets/images/dart.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
