import 'models.dart';

List<Dish> dishes = [

  Dish(
    name: 'Margherita Pizza',
    description: 'Fresh tomatoes, buffalo mozzarella, and basil',
    price: 85.0,
    imageUrl: 'assets/images/pizza.jpg',
    category: 'Pizzas',
    likes: 15,
    dislikes: 2,
    comments: [
      Comment(author: 'Marie', text: 'Delicious and authentic!', date: DateTime.now()),
    ],
  ),
  Dish(
    name: 'Four Cheese Pizza',
    description: 'Mozzarella, gorgonzola, parmesan, and goat cheese',
    price: 95.0,
    imageUrl: 'assets/images/pizza_quatre_fromages.jpeg',
    category: 'Pizzas',
    likes: 22,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Pepperoni Pizza',
    description: 'Spicy pepperoni and melted mozzarella',
    price: 90.0,
    imageUrl: 'assets/images/pizza_pepperoni.jpeg',
    category: 'Pizzas',
    likes: 18,
    dislikes: 3,
    comments: [],
  ),
  Dish(
    name: 'Vegetarian Pizza',
    description: 'Grilled vegetables, mushrooms, and olives',
    price: 88.0,
    imageUrl: 'assets/images/pizza_vegetarienne.jpeg',
    category: 'Pizzas',
    likes: 12,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Seafood Pizza',
    description: 'Shrimp, mussels, and squid',
    price: 120.0,
    imageUrl: 'assets/images/pizza_fruits_mer.jpeg',
    category: 'Pizzas',
    likes: 25,
    dislikes: 2,
    comments: [],
  ),
  Dish(
    name: 'Oriental Pizza',
    description: 'Merguez sausage, peppers, and harissa',
    price: 98.0,
    imageUrl: 'assets/images/pizza_orientale.jpg',
    category: 'Pizzas',
    likes: 20,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Royal Pizza',
    description: 'Ham, mushrooms, and egg',
    price: 105.0,
    imageUrl: 'assets/images/pizza_royale.jpeg',
    category: 'Pizzas',
    likes: 16,
    dislikes: 0,
    comments: [],
  ),

  // BURGERS
  Dish(
    name: 'Classic Burger',
    description: 'Beef patty, lettuce, and tomato',
    price: 75.0,
    imageUrl: 'assets/images/burger.jpg',
    category: 'Burgers',
    likes: 22,
    dislikes: 3,
    comments: [
      Comment(author: 'Paul', text: 'Excellent burger!', date: DateTime.now()),
      Comment(author: 'Sophie', text: 'Great value for money', date: DateTime.now()),
    ],
  ),
  Dish(
    name: 'Cheese Burger',
    description: 'Double beef patty and double cheese',
    price: 85.0,
    imageUrl: 'assets/images/burger_cheese.jpeg',
    category: 'Burgers',
    likes: 28,
    dislikes: 2,
    comments: [],
  ),
  Dish(
    name: 'Chicken Burger',
    description: 'Grilled chicken fillet',
    price: 70.0,
    imageUrl: 'assets/images/burger_chicken.jpeg',
    category: 'Burgers',
    likes: 19,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Fish Burger',
    description: 'Breaded fish fillet',
    price: 78.0,
    imageUrl: 'assets/images/burger_fish.jpeg',
    category: 'Burgers',
    likes: 14,
    dislikes: 4,
    comments: [],
  ),
  Dish(
    name: 'Vegetarian Burger',
    description: 'Plant-based patty and avocado',
    price: 68.0,
    imageUrl: 'assets/images/burger_vegetarien.jpg',
    category: 'Burgers',
    likes: 11,
    dislikes: 2,
    comments: [],
  ),
  Dish(
    name: 'BBQ Burger',
    description: 'Beef patty with BBQ sauce',
    price: 88.0,
    imageUrl: 'assets/images/burger_bbq.jpeg',
    category: 'Burgers',
    likes: 24,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Royal Burger',
    description: 'Triple patty, cheese, and bacon',
    price: 95.0,
    imageUrl: 'assets/images/burger_royal.jpeg',
    category: 'Burgers',
    likes: 30,
    dislikes: 3,
    comments: [],
  ),

  // TAGINES
  Dish(
    name: 'Chicken Tagine with Olives',
    description: 'Slow-cooked chicken with green olives',
    price: 110.0,
    imageUrl: 'assets/images/tajine_poulet_olives.jpeg',
    category: 'Tagines',
    likes: 35,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Lamb Tagine with Prunes',
    description: 'Tender lamb with prunes',
    price: 130.0,
    imageUrl: 'assets/images/tajine_agneau_pruneaux.jpg',
    category: 'Tagines',
    likes: 28,
    dislikes: 2,
    comments: [],
  ),
  Dish(
    name: 'Beef Tagine with Vegetables',
    description: 'Slow-cooked beef with vegetables',
    price: 120.0,
    imageUrl: 'assets/images/tajine_boeuf_legumes.jpeg',
    category: 'Tagines',
    likes: 22,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Fish Tagine with Vegetables',
    description: 'Fresh fish with vegetables',
    price: 125.0,
    imageUrl: 'assets/images/tajine_poisson.jpeg',
    category: 'Tagines',
    likes: 18,
    dislikes: 3,
    comments: [],
  ),
  Dish(
    name: 'Kefta Tagine with Eggs',
    description: 'Meatballs with eggs',
    price: 105.0,
    imageUrl: 'assets/images/tajine_kefta.jpeg',
    category: 'Tagines',
    likes: 26,
    dislikes: 2,
    comments: [],
  ),
  Dish(
    name: 'Vegetarian Tagine',
    description: 'Slow-cooked seasonal vegetables',
    price: 85.0,
    imageUrl: 'assets/images/tajine_vegetarien.jpg',
    category: 'Tagines',
    likes: 15,
    dislikes: 1,
    comments: [],
  ),

  // COUSCOUS
  Dish(
    name: 'Royal Couscous',
    description: 'Lamb, chicken, and merguez sausage',
    price: 140.0,
    imageUrl: 'assets/images/couscous_royal.JPG',
    category: 'Couscous',
    likes: 42,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Lamb Couscous',
    description: 'Tender lamb with vegetables',
    price: 125.0,
    imageUrl: 'assets/images/couscous_agneau.jpeg',
    category: 'Couscous',
    likes: 31,
    dislikes: 2,
    comments: [],
  ),
  Dish(
    name: 'Chicken Couscous',
    description: 'Farm-raised chicken with vegetables',
    price: 115.0,
    imageUrl: 'assets/images/couscous_poulet.jpeg',
    category: 'Couscous',
    likes: 28,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Vegetarian Couscous',
    description: 'Mixed vegetables and chickpeas',
    price: 95.0,
    imageUrl: 'assets/images/couscous_vegetarien.jpg',
    category: 'Couscous',
    likes: 19,
    dislikes: 3,
    comments: [],
  ),

  // DRINKS
  Dish(
    name: 'Sidi Ali Mineral Water',
    description: 'Natural mineral water (50cl)',
    price: 12.0,
    imageUrl: 'assets/images/eau_sidi_ali.jpg',
    category: 'Drinks',
    likes: 8,
    dislikes: 0,
    comments: [],
  ),
  Dish(
    name: 'Coca-Cola',
    description: 'Carbonated drink (33cl)',
    price: 15.0,
    imageUrl: 'assets/images/coca_cola.jpg',
    category: 'Drinks',
    likes: 12,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Fresh Orange Juice',
    description: 'Freshly squeezed orange juice (25cl)',
    price: 20.0,
    imageUrl: 'assets/images/jus_orange.jpg',
    category: 'Drinks',
    likes: 18,
    dislikes: 0,
    comments: [],
  ),
  Dish(
    name: 'Mint Tea',
    description: 'Traditional green tea with mint',
    price: 18.0,
    imageUrl: 'assets/images/the_menthe.jpeg',
    category: 'Drinks',
    likes: 25,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Espresso Coffee',
    description: 'Italian espresso coffee',
    price: 15.0,
    imageUrl: 'assets/images/cafe_espresso.JPG',
    category: 'Drinks',
    likes: 14,
    dislikes: 2,
    comments: [],
  ),
  Dish(
    name: 'Homemade Lemonade',
    description: 'Handcrafted lemonade',
    price: 22.0,
    imageUrl: 'assets/images/limonade.jpg',
    category: 'Drinks',
    likes: 16,
    dislikes: 0,
    comments: [],
  ),
  Dish(
    name: 'Red Berry Smoothie',
    description: 'Mixed red fruits smoothie (30cl)',
    price: 35.0,
    imageUrl: 'assets/images/smoothie_fruits_rouges.JPG',
    category: 'Drinks',
    likes: 21,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Mango Lassi',
    description: 'Yogurt-based mango drink',
    price: 28.0,
    imageUrl: 'assets/images/lassi_mangue.jpeg',
    category: 'Drinks',
    likes: 13,
    dislikes: 2,
    comments: [],
  ),

  // DESSERTS
  Dish(
    name: 'Tiramisu',
    description: 'Italian coffee dessert',
    price: 45.0,
    imageUrl: 'assets/images/tiramisu.jpg',
    category: 'Desserts',
    likes: 18,
    dislikes: 0,
    comments: [],
  ),
  Dish(
    name: 'Baklava',
    description: 'Oriental pastry with almonds',
    price: 35.0,
    imageUrl: 'assets/images/baklava.jpeg',
    category: 'Desserts',
    likes: 22,
    dislikes: 1,
    comments: [],
  ),
  Dish(
    name: 'Crème Brûlée',
    description: 'Vanilla custard with caramelized top',
    price: 40.0,
    imageUrl: 'assets/images/creme_brulee.jpeg',
    category: 'Desserts',
    likes: 19,
    dislikes: 0,
    comments: [],
  ),
];
